language: python
python: 3.6
install:
- pip install mkdocs
script:
- mkdocs build --strict --verbose
- touch ./site/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  # configured as an env var in travis CI, currently via a github personal access token for lbryan-citrine
  # current token expires May 18, 2023
  github_token: "$GH_SECRET_TOKEN"
  keep_history: true
  local_dir: "./site/"
  on:
    branch: master
