site_name: GEMD Documentation
theme: readthedocs
site_url: https://citrineinformatics.github.io/gemd-docs
markdown_extensions:
    - toc:
        baselevel: 1
        toc_depth: 4
        permalink: True

extra:
    version: 0.1
