name: PR Checks

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  check-docs:
    name: Check docs for warnings
    runs-on: ubuntu-latest
    steps:
      - name: Initialize the environment
        continue-on-error: true
        uses: ./.github/actions/initialize
      - name: Build Docs
        continue-on-error: true
        run: mkdocs build --strict --verbose
